# Generated by Django 3.2.16 on 2022-10-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20221027_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='date_of_register',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
