# Generated by Django 3.2.16 on 2022-10-27 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_complaint_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='user',
        ),
    ]
