# Generated by Django 3.2.16 on 2022-10-31 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_auto_20221031_0655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='name',
        ),
    ]
