# Generated by Django 3.2.16 on 2022-10-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_remove_complaint_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
