# Generated by Django 3.2.16 on 2022-11-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_complaint_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('number', models.CharField(max_length=10, null=True)),
                ('age', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
